version: "3.9"

services:
  inventory-db:
    container_name: inventory-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_INVENTORY_USER}
      POSTGRES_PASSWORD: ${DB_INVENTORY_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_INVENTORY_NAME}
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_INVENTORY_PORT}:5432"
    restart: unless-stopped

  inventory-app:
    container_name: inventory-app
    build: .
    environment:
      DB_INVENTORY_HOST: inventory-db
      DB_INVENTORY_PORT: ${DB_INVENTORY_PORT}
      DB_INVENTORY_NAME: ${DB_INVENTORY_NAME}
      DB_INVENTORY_USER: ${DB_INVENTORY_USER}
      DB_INVENTORY_PASSWORD: ${DB_INVENTORY_PASSWORD}
      APP_INVENTORY_PORT: ${APP_INVENTORY_PORT}
    ports:
      - "8081:${APP_INVENTORY_PORT}"
    depends_on:
      - inventory-db

volumes:
  postgres: