name: CI/CD for API Gateway

on:
  push:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      api_gateway_changed: ${{ steps.check.outputs.api_gateway_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in api-gateway
        id: check
        run: |
          echo "::set-output name=api_gateway_changed::$(git diff --name-only HEAD^ HEAD | grep -q 'srcs/api-gateway' && echo true || echo false)"

  api_gateway_build_and_push:
    runs-on: ubuntu-latest
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.api_gateway_changed == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.USERNAME }}/api-gateway:latest srcs/api-gateway

      - name: Push Docker image
        run: |
          docker push ${{ secrets.USERNAME }}/api-gateway:latest
